AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito Stack

Parameters:
  AuthName:
    Type: String
    Description: Unique Auth Name for Cognito Resources


Resources:
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub ${AuthName}-user-pool
#      AutoVerifiedAttributes:
#        - email
      AliasAttributes:
        - email
        - preferred_username
      EmailVerificationSubject: "Confirmação de cadastro na SMILE 2022"
      EmailVerificationMessage: "Olá,\n\nPara confirmar seu cadastro na SMILE 2022, use o código: {####} ou clique no link: LINK_FUTURO \n\nAtenciosamente,\nEquipe SMILE 2022"
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: cpfRne
          AttributeDataType: String
          Mutable: false
          Required: false
        - Name: ra
          AttributeDataType: String
          Mutable: false
          Required: false
        - Name: accessLevel
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false


  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub ${AuthName}-client
      GenerateSecret: false
      AccessTokenValidity: 24 #hours
      RefreshTokenValidity: 7 #days
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH


Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: "UserPool::Id"
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: "UserPoolClient::Id"
